<a href="https://colab.research.google.com/github/PrajwalKerudi/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import numpy as np

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
#.How do you check the version and configuration of NumPy?

import numpy as np
print(np.__version__)


2.0.2


In [ ]:
#How do you create a vector filled with zeros of size 10?

import numpy as np
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#How do you find help/documentation for a NumPy function from the command line?

import numpy as np
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, 

In [ ]:
#How do you create a zero vector of size 10 with the fifth element as 1

import numpy as np
vector = np.zeros(10)
vector[5] = 1
print(vector)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [ ]:
#How do you create a vector with values from 10 to 49

import numpy as np
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# How do you reverse a vector?

import numpy as np
vector = np.arange(10,50)
vector = vector[::-1]
print(vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#How do you create a 3x3 matrix with values from 0 to 8

import numpy as np
matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#.How do you find indices of non-zero elements in an array

import numpy as np
array = np.array([1,2,0,0,4,0])
indices = np.nonzero(array)
print(indices)

(array([0, 1, 4]),)


In [ ]:
#How do you create a 3x3 identity matrix

import numpy as np
matrix = np.eye(3)
print(matrix)

In [ ]:
#How do you generate a 3x3x3 array with random values?

import numpy as np
array = np.random.rand(3,3,3)
print(array)

[[[0.58964631 0.47482236 0.67401204]
  [0.76888013 0.89002491 0.64785634]
  [0.63978862 0.8811022  0.94529013]]

 [[0.57447715 0.97521112 0.67054628]
  [0.14116196 0.23463044 0.39237593]
  [0.95735835 0.85627511 0.74664525]]

 [[0.58672874 0.46077852 0.04813728]
  [0.44922644 0.86456844 0.71907364]
  [0.08278514 0.64197619 0.60286403]]]


In [ ]:
#How do you find the min and max values in a 10x10 random matrix

import numpy as np
matrix = np.random.rand(10,10)
min_value = np.min(matrix)
max_value = np.max(matrix)
print("min_value") == min_value
print("max_value") == max_value

Matrix:
 [[0.71729624 0.1144299  0.28164337 0.9387178  0.94592941 0.69543224
  0.91506022 0.62369382 0.93542351 0.86804871]
 [0.95970131 0.67924034 0.88169195 0.5075628  0.80696216 0.18319984
  0.7325639  0.85643933 0.70479223 0.37802955]
 [0.55954471 0.79195378 0.92418748 0.73540763 0.317461   0.97945541
  0.8255542  0.0926626  0.93353313 0.04303792]
 [0.57012823 0.57131226 0.25207916 0.58716255 0.90994749 0.6966571
  0.30803214 0.90937227 0.51240162 0.72053279]
 [0.26826796 0.66517546 0.26819543 0.07471146 0.22667762 0.20844842
  0.37171024 0.43417797 0.3644747  0.12858003]
 [0.14298657 0.67089467 0.45188317 0.54817048 0.3374305  0.95016705
  0.86172273 0.72345775 0.72276612 0.81333658]
 [0.34897068 0.11987945 0.0045084  0.31665969 0.83816829 0.15270347
  0.04110165 0.99289599 0.39281493 0.45770106]
 [0.24189893 0.7728572  0.85466726 0.0659372  0.84038937 0.78851382
  0.42931526 0.87042204 0.02524523 0.93341794]
 [0.69765302 0.47927332 0.10386147 0.92489699 0.0171756  0.9955162
  0.2

In [ ]:
#How do you calculate the mean of a random vector of size 30

import numpy as np
vector = np.random.rand(30)
mean_value = np.mean(vector)
print(mean_value)

0.48261255935204894


In [ ]:
#How do you create a 2D array with 1s on the border and 0s inside

import numpy as np
array = np.ones((5,5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#What is the result of operations like 0 * np.nan, np.nan == np.nan, etc.

import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan != np.nan)

nan
False
False
True


In [ ]:
#How do you create a matrix with values below the diagonal

import numpy as np
matrix = np.diag(np.arange(1,5), k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
#.How do you create a checkerboard pattern in an 8x8 matrix

import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#How do you find the index of a flat element in a 3D shape

import numpy as np
array = np.random.rand(3,3,3)
index = np.unravel_index(np.argmax(array), array.shape)
print(index)


(np.int64(1), np.int64(1), np.int64(1))


In [ ]:
#How do you create a checkerboard pattern using NumPy's tile function

import numpy as np
checkerboard = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(checkerboard, (4, 4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#How do you normalize a matrix (values between 0 and 1)

import numpy as np
matrix = np.random.rand(5,5)
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
print(normalized_matrix)

[[0.97547683 0.73476441 0.88395619 0.86120514 0.96639364]
 [0.52838806 0.01771476 0.         0.66856795 0.01431376]
 [0.92839078 0.56526672 0.2149387  0.30530315 0.97396328]
 [0.54541886 1.         0.89390505 0.48340088 0.98450878]
 [0.57174125 0.73018272 0.92100711 0.09344759 0.33568618]]


In [ ]:
#How do you define a custom data type for storing color (RGBA)?

import numpy as np
color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [ ]:
#How do you perform a matrix multiplication between two matrices?

import numpy as np
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print(result)

[[19 22]
 [43 50]]


In [ ]:
#How do you negate values between two given numbers in a vector

import numpy as np
vector = np.arange(10)
vector[(vector >= 3) & (vector <= 7)] *= -1
print(vector)

[ 0  1  2 -3 -4 -5 -6 -7  8  9]


In [ ]:
#What is the output of sum(range(5), -1) vs np.sum(range(5), -1)

import numpy as np
print(sum(range(5), -1))
print(np.sum(range(5), -1))

9
10


In [ ]:
#Which NumPy vector operations are legal or illegal

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # ✅ legal
print(a * b)   # ✅ legal



[5 7 9]
[ 4 10 18]


In [ ]:
#What happens when you divide integers or floats by zero in NumPy

import numpy as np

a = np.array([1, 2, 3])
b = np.array([0, 0, 0])

print(a // b)   # integer division


[0 0 0]


/tmp/ipython-input-3232723593.py:8: RuntimeWarning: divide by zero encountered in floor_divide
  print(a // b)   # integer division


In [ ]:
#How do you round a float array away from zero

import numpy as np

a = np.array([1.2, -1.2, 1.7, -1.7])

rounded = np.copysign(np.ceil(np.abs(a)), a)
print(rounded)


[ 2. -2.  2. -2.]


In [ ]:
#How do you extract the integer part of a float using multiple methods

import numpy as np

a = np.array([1.7, -2.9, 3.5, -4.1])


In [ ]:
np.trunc(a)


array([ 1., -2.,  3., -4.])

In [ ]:
np.floor(a)


array([ 1., -3.,  3., -5.])

In [ ]:
#How do you create a 5x5 matrix with row values ranging from 0 to 4

import numpy as np

matrix = np.tile(np.arange(5), (5, 1))
print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
#.How do you use a generator to create a NumPy array

import numpy as np

gen = (i for i in range(10))

arr = np.fromiter(gen, dtype=int)

print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#How do you create an array with evenly spaced values between 0 and 1 (excluded)

import numpy as np

arr = np.linspace(0, 1, num=6, endpoint=False)[1:]
print(arr)


[0.16666667 0.33333333 0.5        0.66666667 0.83333333]


In [ ]:
#How do you sort a random array

import numpy as np

arr = np.random.randint(1, 100, size=10)
print("Original array:", arr)


Original array: [ 4 80  7  6 80 75 17 77 36 80]


In [ ]:
#How do you sum an array faster than using np.sum

import numpy as np

arr = np.random.rand(10_000_000)

arr.sum()


np.float64(4999531.402540887)

In [ ]:
#How do you check if two arrays are equal

import numpy as np

a = np.array([1, 2, 3])
b = np.array([1, 2, 4])

print(a == b)


[ True  True False]


In [ ]:
#How do you make a NumPy array read-only

import numpy as np

arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#How do you convert Cartesian coordinates to polar coordinates

import numpy as np

x = np.array([1, 0, -1])
y = np.array([0, 1, 1])

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
print("r =", r)
print("theta (radians) =", theta)
print("theta (degrees) =", np.degrees(theta))


r = [1.         1.         1.41421356]
theta (radians) = [0.         1.57079633 2.35619449]
theta (degrees) = [  0.  90. 135.]


In [ ]:
#How do you replace the maximum value in an array with zero

import numpy as np

arr = np.array([3, 7, 2, 9, 5])
print("Original:", arr)

arr[arr == arr.max()] = 0
print("Modified:", arr)


Original: [3 7 2 9 5]
Modified: [3 7 2 0 5]


In [ ]:
#How do you create a structured array for (x, y) coordinate pairs

import numpy as np

coord_dtype = np.dtype([('x', float), ('y', float)])


In [ ]:
points = np.array([(1.0, 2.0), (3.5, 4.2), (5.1, 7.3)], dtype=coord_dtype)
print(points)


[(1. , 2. ) (3.5, 4.2) (5.1, 7.3)]


In [ ]:
print(points['x'])
print(points['y'])


[1.  3.5 5.1]
[2.  4.2 7.3]


In [ ]:
points['x'] += 10
print(points)


[(11. , 2. ) (13.5, 4.2) (15.1, 7.3)]


In [ ]:
#How do you create a Cauchy matrix using two arrays

import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

C = 1.0 / (x[:, np.newaxis] - y)
print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


In [ ]:
#How do you find the range of values for each NumPy scalar type

import numpy as np

info = np.iinfo(np.int32)
print("int32 range:", info.min, "to", info.max)


int32 range: -2147483648 to 2147483647


In [ ]:
#How do you display all values in a large array

import numpy as np

arr = np.arange(100)
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
#How do you find the closest value to a given scalar in an array

import numpy as np

arr = np.array([10, 22, 14, 3, 7])
value = 12

closest = arr[np.abs(arr - value).argmin()]
print("Closest value:", closest)


Closest value: 10


In [ ]:
#How do you create a structured array with position and color fields

import numpy as np

dtype = np.dtype([
    ('position', float, 3),
    ('color', float, 4)
])


In [ ]:
data = np.array([
    ((1.0, 2.0, 3.0), (1.0, 0.0, 0.0, 1.0)),
    ((4.0, 5.0, 6.0), (0.0, 1.0, 0.0, 1.0)),
    ((7.0, 8.0, 9.0), (0.0, 0.0, 1.0, 1.0))
], dtype=dtype)

print(data)


[([1., 2., 3.], [1., 0., 0., 1.]) ([4., 5., 6.], [0., 1., 0., 1.])
 ([7., 8., 9.], [0., 0., 1., 1.])]


In [ ]:
#.How do you compute pairwise distances between coordinates

import numpy as np

points = np.array([
    [0, 0],
    [3, 4],
    [6, 8]
])

In [ ]:
from scipy.spatial import distance

dist_matrix = distance.cdist(points, points)
print(dist_matrix)

[[ 0.  5. 10.]
 [ 5.  0.  5.]
 [10.  5.  0.]]


In [ ]:
#How do you cast a float array to integer type in place

import numpy as np

arr = np.array([1.2, 3.7, 5.9])
print(arr, arr.dtype)


[1.2 3.7 5.9] float64


In [ ]:
#How do you read data from a file with missing values

import numpy as np

data = np.genfromtxt('data.csv', delimiter=',', missing_values='', filling_values=np.nan)
print(data)


[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8. nan]
 [nan 10. 11.]]


In [ ]:
# Create a dummy data.csv file for demonstration
with open('data.csv', 'w') as f:
    f.write('1,2,3\n')
    f.write('4,,6\n')
    f.write('7,8,\n')
    f.write(',10,11\n')

In [ ]:
# How do you read data from a file with missing values

import numpy as np

data = np.genfromtxt('data.csv', delimiter=',', missing_values='', filling_values=np.nan)
print(data)

[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8. nan]
 [nan 10. 11.]]


In [ ]:
#How do you iterate through all elements in a NumPy array with indices

import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

for index, value in np.ndenumerate(arr):
    print(index, value)


(0, 0) 10
(0, 1) 20
(0, 2) 30
(1, 0) 40
(1, 1) 50
(1, 2) 60


In [ ]:
#How do you create a 2D Gaussian-like array

import numpy as np

n = 7
sigma = 1.0

x = np.linspace(-3, 3, n)
y = np.linspace(-3, 3, n)
x, y = np.meshgrid(x, y)

gaussian = np.exp(-(x**2 + y**2) / (2 * sigma**2))

gaussian /= np.max(gaussian)

print(np.round(gaussian, 3))


[[0.    0.002 0.007 0.011 0.007 0.002 0.   ]
 [0.002 0.018 0.082 0.135 0.082 0.018 0.002]
 [0.007 0.082 0.368 0.607 0.368 0.082 0.007]
 [0.011 0.135 0.607 1.    0.607 0.135 0.011]
 [0.007 0.082 0.368 0.607 0.368 0.082 0.007]
 [0.002 0.018 0.082 0.135 0.082 0.018 0.002]
 [0.    0.002 0.007 0.011 0.007 0.002 0.   ]]


In [ ]:
#How do you randomly place a specific number of elements in a 2D array

import numpy as np

rows, cols = 5, 5
num_elements = 5


In [ ]:

arr = np.zeros((rows, cols), dtype=int)

indices = np.random.choice(arr.size, num_elements, replace=False)

arr.flat[indices] = 1

print(arr)


[[0 1 1 0 0]
 [0 1 1 0 0]
 [0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]


In [ ]:
#How do you subtract the row mean from a matrix

import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=float)


In [ ]:
A_centered = A - A.mean(axis=1, keepdims=True)
print(A_centered)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [1]:
# How do you sort a 2D array based on the values of one column

import numpy as np

arr = np.array([
    [10, 2, 9],
    [5, 1, 7],
    [8, 3, 6]
])

sorted_arr = arr[arr[:, 1].argsort()]

print("Original array:\n", arr)
print("\nSorted by column 1:\n", sorted_arr)


Original array:
 [[10  2  9]
 [ 5  1  7]
 [ 8  3  6]]

Sorted by column 1:
 [[ 5  1  7]
 [10  2  9]
 [ 8  3  6]]


In [2]:
#How do you check if a 2D array contains any null (zero-only) columns

import numpy as np

arr = np.array([
    [0, 2, 0],
    [0, 3, 0],
    [0, 4, 0]
])
null_columns = np.all(arr == 0, axis=0)

print("Zero-only columns mask:", null_columns)
print("Any zero-only columns present?:", np.any(null_columns))


Zero-only columns mask: [ True False  True]
Any zero-only columns present?: True


In [3]:
#How do you find the nearest value to a given number in a NumPy array

import numpy as np

arr = np.array([3.5, 8.2, 1.7, 6.4, 9.9])

target = 7.0

nearest_value = arr[np.abs(arr - target).argmin()]

print("Array:", arr)
print("Target:", target)
print("Nearest value:", nearest_value)


Array: [3.5 8.2 1.7 6.4 9.9]
Target: 7.0
Nearest value: 6.4


In [4]:
#How do you create a NumPy subclass with custom attributes

import numpy as np

class MyArray(np.ndarray):
    def __new__(cls, input_array, info=None):
        obj = np.asarray(input_array).view(cls)
        obj.info = info
        return obj

    def __array_finalize__(self, obj):

        if obj is None: return
        self.info = getattr(obj, 'info', None)

arr = MyArray([1, 2, 3, 4, 5], info="My custom data")

print("Array:", arr)
print("Type:", type(arr))
print("Custom attribute:", arr.info)


Array: [1 2 3 4 5]
Type: <class '__main__.MyArray'>
Custom attribute: My custom data


In [5]:
#How do you increment elements in an array using an index array with repeats

import numpy as np

arr = np.zeros(5, dtype=int)

idx = np.array([0, 1, 1, 2, 2, 2, 4])

np.add.at(arr, idx, 1)

print(arr)


[1 2 3 0 1]


In [6]:
#How do you accumulate values into an array based on indices

import numpy as np

indices = np.array([0, 1, 1, 2, 2, 2, 4])

values = np.array([10, 20, 30, 40, 50, 60, 70])

result = np.zeros(5, dtype=int)

np.add.at(result, indices, values)

print("Accumulated result:", result)


Accumulated result: [ 10  50 150   0  70]


In [7]:
#How do you count unique colors in a 3D image array

import numpy as np

img = np.array([
    [[255, 0, 0], [0, 255, 0], [0, 0, 255]],
    [[255, 0, 0], [255, 0, 0], [0, 255, 0]],
    [[0, 0, 255], [0, 0, 255], [255, 255, 255]]
], dtype=np.uint8)

pixels = img.reshape(-1, 3)

unique_colors = np.unique(pixels, axis=0)

print("Unique colors:\n", unique_colors)
print("Number of unique colors:", len(unique_colors))


Unique colors:
 [[  0   0 255]
 [  0 255   0]
 [255   0   0]
 [255 255 255]]
Number of unique colors: 4


In [8]:
#How do you compute the sum across the last two axes of a 4D array

import numpy as np

arr = np.random.rand(2, 3, 4, 5)

result = np.sum(arr, axis=(-2, -1))

print("Original shape:", arr.shape)
print("Result shape:", result.shape)


Original shape: (2, 3, 4, 5)
Result shape: (2, 3)


In [9]:
#How do you calculate means of grouped values in an array

import numpy as np
groups = np.array([0, 1, 0, 1, 2, 2, 2])

values = np.array([10, 20, 30, 40, 50, 60, 70])


In [10]:
sum_per_group = np.bincount(groups, weights=values)
count_per_group = np.bincount(groups)

mean_per_group = sum_per_group / count_per_group
print(mean_per_group)


[20. 30. 60.]


In [11]:
#How do you efficiently get the diagonal of a matrix dot product

import numpy as np

A = np.random.rand(1000, 500)
B = np.random.rand(500, 1000)

diag_AB = np.sum(A * B.T, axis=1)


In [12]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

diag_full = np.diag(A @ B)
diag_fast = np.sum(A * B.T, axis=1)

print("Full method:", diag_full)
print("Efficient method:", diag_fast)


Full method: [0.97370804 1.43345021 0.96670951]
Efficient method: [0.97370804 1.43345021 0.96670951]
